### ISSUE TITLE
Volume Slider UI on Mobile

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#102]
Maybe worth a discussion if this UI component should be shown at all if the device does not support changing volume via software. iPhone and other mobile devices can only change the volume via hardware buttons.

**Comment by cjpillsbury** [comment]
Agree 100% we should definitely handle this somehow. I'd lean toward having this driven by an attribute/prop that by default is set to autohide via default css if volume is unsupported (at least some of the "ownership" of this will have to be in `media-volume-range` since the controls may not be descendants of a `media-controller`). We can discuss in detail and create a new feature request issue or move this over to discussions if we want to iron out the details here on github.

**Comment by heff** [comment]
We might also want to consider a "disabled" state for every UI element. It seems natural to hide the control in the context of a control bar or player, but it could be unexpected if the control disappears when it's standing on its own.

**Comment by cjpillsbury** [comment]
Relates to #134 
Relates to #135

**Comment by luwes** [comment]
Solved in https://github.com/muxinc/media-chrome/pull/156 🎉
