### ISSUE TITLE
Add dimensions (and aspect-ratio maybe) style to examples

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#103]
The examples show serious layout shift on page load at the moment.
https://media-chrome.mux.dev/examples/basic.html

**Comment by cjpillsbury** [comment]
I think this is a deeper issue that we should see if we can solve "under the hood" 😬. See: https://github.com/muxinc/media-chrome/blob/main/src/js/media-container.js#L53-L73

**Comment by luwes** [comment]
I'm not sure here, it's related to that the JS is too slow to execute before the video tag expands due to the video source's dimensions. After that the JS is executed and it shrinks the video element back down. Try running the page with JS disabled, then you can see that the video element expands all the way.

Related url: https://web.dev/optimize-cls/#images-without-dimensions

Maybe it makes a difference to use a `<script>` tag without `type="module"` but yea that's not ideal.

> Module scripts behave like defer by default – there's no way to make a module script block the HTML parser while it fetches.

**Comment by heff** [comment]
Talked with Christian about this a bit this morning. He was thinking the answer might be to remove the default 720x480 dimensions of the container, and follow [the example of `<mux-video>`](https://github.com/muxinc/elements/blob/main/packages/mux-video/src/CustomVideoElement.js) with:
```
  video {
    max-width: 100%;
    max-height: 100%;
    min-width: 100%;
    min-height: 100%;
  }
```

The desired result, from my perspective would be:

1. If the developer sets a width and height for `<media-controller>` using CSS, then the slotted video element fills the controller/container dimensions. 
2. If the developer does not set a width and hight for `<media-controller>`, media-controller fits the native size of the slotted video element.

For the example specifically, I think we're either choosing a smaller video or setting a width and height for the controller. Because the solution above would leave the video massive.

**Comment by luwes** [comment]
Sounds like a good solution, it's quite rare where the consumer wouldn't set the dimensions of a parent container I think.
And safer or less unpredictable to stick to native HTML behaviors otherwise.
