### ISSUE TITLE
Muted icon not showing 

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#140]
A `<video muted>` should show the muted icon in the mute button on page load.

https://codepen.io/luwes/pen/yLPypdG?editors=1000

This worked in v0.2
https://codepen.io/luwes/pen/vYWEdgJ?editors=1000

**Comment by heff** [comment]
Took me a bit to follow the bread crumbs, but it looks like we just forgot to add a media volume level propagator ([we have media volume](https://github.com/muxinc/media-chrome/blob/main/src/js/media-controller.js#L514), but not volume level). 

Maybe it was partially intentional?
It looks like the propagators we have when a new element is registered duplicate logic for determining the current state, which is also in _mediaStatePropagators. That's not a great long term solution, and makes volume level a more complicated one because it's not just a simple media element API call.

I think what we need first is a public `volumeLevel` API, that both of these internal functions can all. We have the [volume](https://github.com/muxinc/media-chrome/blob/main/src/js/media-controller.js#L569) API already.
