### ISSUE TITLE
CSS background vars

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#141]
Not a biggie but in media-chrome I noticed a CSS var `--media-control-background` for the buttons and it’s set to the `background-color` property. 

In a bunch of places in the themes etc this var is set to `none` but strictly that’s not valid CSS. 
Should be `transparent`.
https://stackoverflow.com/a/8739704/268820

Maybe look into setting this CSS prop to the CSS shorthand `background` for more customization options.

**Comment by heff** [comment]
Good catch, and yeah, let's move it to the more flexible `background`. In general we should align the var name with the specific css prop, unless we have a good reason not to. 

Relatedly, we should also change `--media-range-track-background` to `--media-range-track-background-color`, because in that case it's used to [create a gradient](https://github.com/muxinc/media-chrome/blob/main/src/js/media-chrome-range.js#L31), and so it has to be a color.
