### ISSUE TITLE
Access to events emitted

### ISSUE THREAD

**Issue by Nodalailama** [muxinc/media-chrome#41]
Hi,

Is there a way to access to events emitted by a media controller? 

For example, I need to know when the player go fullscreen. 
May you can emit an event attach to window with the id of the player element? 
like so "enterFullscreen-myMediaControllerId@window"

How can I manage the dooble click to enter then exit fullscreen ?

Cordialement,

**Comment by dylanjha** [comment]
Hi @Nodalailama -- good question.

The `media-controller` element itself is the element that requests full screen from the browser, so that is the element that emits the brower's built-in full screen events. So right now the best way to get what you're going for is to set up a listener on the `<media-controller>` element itself:

The one thing about full-screen events is that safari calls it `webkitfullscreenchange` whereas other browsers use `fullscreenchange`.

```
const mediaController = document.querySelector("media-controller");

// if document.fullscreenElement is undefined, then use 'webkitfullscreenchange'
if (typeof document.fullscreenElement === "undefined") {
  mediaController.addEventListener("webkitfullscreenchange", function () {
    console.log("entered full screen on webkitfullscreenchange");
  });
} else {
  mediaController.addEventListener("fullscreenchange", function () {
    console.log("entered full screen on fullscreenchange");
  });
}
```

Let me know if this helps, here's a codesandbox with an example (see index.js): https://codesandbox.io/s/media-chrome-w-mp4-slot-3l4ry

**Comment by Nodalailama** [comment]
Hi,

Thanks for quickly replied, I gonna implement that and I will come back to you.

Cordialement,

**Comment by Nodalailama** [comment]
Hi,

It work. Using stimulus, I register "webkitfullscreenchange" and "fullscreenchange" events action, 
the browser know the good one to use.

Thanks.
