### ISSUE TITLE
Emit events from media-controller

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#46]
Related to #41 we should re-emit the media events that happen so that applications can have a central source for them, rather than needing to listen to the media element itself (which could change). 

This gets a little complicated with fullscreenchange events, because those actually happen on the media-controller itself. Ideally we can unify the event name rather than requiring the browser-specific solution in #41.

**Comment by mmcc** [comment]
That's a good point re: the media being able to change underneath. Example would be if someone made a playlist component (which now that I say it might be a good one to build early so we can understand that workflow).

**Comment by heff** [comment]
Yeah, definitely. I've thought about playlists a bit and that's a bit interesting. The options I see are either building it directly into media-controller and allowing you to add multiple els with slot="media", or building a `<media-playlist slot="media">` el that implements the video API. Kind of comes down to if we want the default of multiple media slots to be a playlist or sync playback. Either way we can resurrect [x-playlist](https://github.com/heff/x-playlist). :)

**Comment by luwes** [comment]
wondering if this is still an issue?

since the media attribute events have been added in PR https://github.com/muxinc/media-chrome/pull/182
and we decided MediaController should not imitate a native media element 

the [`media-playlist`](https://github.com/muxinc/media-playlist) element seems to do the job that was questioned here, emitting events of the changing media elements
