### ISSUE TITLE
Text Track Data

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#59]
Q: How do we pass text track data (captions, subtitles) in to the menus and other elements that need it?

Assumptions:
* At the the UI (chrome) level we are not overlaying the captions on the media, that's the job of the media element
* We may still want access to the text track cues, to display outside of the player or do something interesting based on a metadata track.

Important text track details:
* `srclang` is required when `kind` is set
* `label` is not required
* "A media element cannot have more than one track with the same kind, srclang, and label."
* Tracks can be `disabled`, `hidden` (still active and usable), and `showing`
* Multiple tracks of the same kind can be `showing`

### Available tracks list:
* One attr per 'kind' of track (Menus can choose to combine the lists if desired)
```html
<media-ui-el media-captions-list="..." media-subtitles-list="..." >
```
* Comma-separated list with URL-encoded optional label value

```html
<media-ui-el media-captions-list="en-US:English en:English%20%28with%20descriptions%29">

Min required
<media-ui-el media-captions-list="en">
```

### Selected track(s)
```html
<media-ui-el media-captions-showing="en-US es">
```

**Comment by dylanjha** [comment]
> At the the UI (chrome) level we are not overlaying the captions on the media, that's the job of the media element

Is this a long term assumption? Or is this a "for now" assumption. "For now" we'll rely on the media element to be responsible for overlaying, but we may want to have `media-chrome` take over that responsibility in the future.

A practical reason I ask, consider the following example:

* media element correctly shows the captions track by overlaying it at the bottom of the video
* users hovers and media-chrome's `<media-control-bar>` element slides up from the bottom, covering the captions track

An ideal experience would work like this:


https://user-images.githubusercontent.com/764988/132995106-6bd7336e-6d71-43d6-8705-f1c524b51d46.mp4



In order to pull that off, one of two things needs to happen:

(1) The media element is aware that the control bar is showing, and adjusts the captions overlay accordingly
(2) `media-chrome` is in control of the overlay the whole time

---

(1) I think would break our current paradigm because the media-element would have to know about the state inside `<media-controller>`, and know where the control bar is positioned, if it's showing, etc. It's also unclear how a common media element like the default `<video>` element would easily adjust the captions overlay to make room for controls (as far as I can't tell it's not easy to simply adjust the positioning of cues.

(2) Opens up a giant 🐰 🕳️ . WebVTT can [contain positional information for each cue](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings) -- so does that mean that when the control bar slides up we ignore cue positional information? What if the control bar not at the bottom? How do we handle that?

I think the right answer for the time being is to go with the mentioned assumption, but I just wanted to bring this up because it does feel like a shortcoming we will be running into.

> At the the UI (chrome) level we are not overlaying the captions on the media, that's the job of the media element

**Comment by cjpillsbury** [comment]
> (1) The media element is aware that the control bar is showing, and adjusts the captions overlay accordingly

I'm a little concerned about introducing this. Currently, while `<media-controller/>` defines some default layout via CSS, its primary purpose is a bridge between player state and ui components. Introducing (1) doesn't just break the architectural paradigms we're aiming for, it also adds a completely different kind of state management. I think this might be making `<media-controller/>` "do too many things", but, if we do go down that path, we'll have to think about the implications. A few simple examples "off the dome": `<media-control-bar/>` doesn't really "do much" right now, and someone could theoretically just use e.g. a `<div/>` with whatever styling they wanted instead. Similarly, we don't "know" where/how the `<media-control-bar/>` will be sized/positioned (since that's entirely managed by CSS+DOM structure right now), so e.g. implementors may want some or all controls positioned on the top, on the top and the bottom, on the top when on smaller devices, etc.

> (2) Opens up a giant 🐰 🕳️ . WebVTT can contain positional information for each cue -- so does that mean that when the control bar slides up we ignore cue positional information?

This is "less scary" to me, but rather than "mucking around" with cue positional information, we'd probably want to fully managing the rendering + render region for cues (a la https://github.com/mozilla/vtt.js or similar) for now (if we wanted to support this). Longer term, assuming consistent browser support in the future, we could likely rely on VTTRegion (see: https://developer.mozilla.org/en-US/docs/Web/API/VTTRegion but also, see: https://caniuse.com/mdn-api_vttregion).

**Comment by heff** [comment]
This all makes sense. In my mind captions ride the line between UI and media content. Burned in hard subs or intentionally positioned/styled captions are part of the content, whereas captions where a viewer expects to be able to tweak the colors, size etc. of the captions starts to look more UI. From a technology perspective ideally we don't have to mess with captions because they're complicated and browsers do a decent job on their own. But I can see needing to address the UI aspects like Dylan's example. Unless we decide that relying on browsers is unacceptable for most use case, the default media-chrome example should rely on browsers, but we can still build elements to support advanced caption-related features.

For the controls example specifically, ignoring what's possible, I think what we'd want is a way to say to the media element "avoid this area". VTT Region looks close but I can't tell if you can create a region that default accepts any captions, as opposed to needing to be specific about what caption cues go into a region. It's worth understanding if that could be the real solution here and pushing the standards while patching them somehow until they're supported in Chrome. 

Otherwise what I could see doing is creating a `<media-captions>` element that overlays the full media element and uses vtt.js for layout. It could also include an option to change the captions region on hover/pause (when controls would be showing). But I think it'd be up to players (using media chrome) or themes to make sure the control bar size and the adjusted caption region match, rather than trying to solve that completely at the media-chrome level and creating a complicated relationship between elements.

**Comment by heff** [comment]
@cjpillsbury it feels like we can close this one, yeah? I think we've implemented the major concepts, and even worked towards a solution to the last note on adjusting the captions location, via the middle chrome section.

**Comment by cjpillsbury** [comment]
Closing. Data relationship implemented. Alternate render target for captions/subtitles. should be treated as a separate issue/feature discussion if/when we try to support it.
