### ISSUE TITLE
Media playback rate button ignores custom rates

### ISSUE THREAD

**Issue by mskorsur** [muxinc/media-chrome#679]
Hello,

The media playback rate button ignores the custom values set for the rates attribute and uses the default values only.
Seems like some check whether there are custom rates set is not correct and default values are always used.
The version on which this issue occurred is 1.1.2.

Thanks for taking a look!

**Comment by heff** [comment]
Hi! What values are you using? Custom rates are working for me in [this example](https://codepen.io/heff/pen/dyQVXQQ?editors=1000).

But in testing that I found:
* The starting value is always 1x, not matter if the options don't include a 1x. That might be unavoidable since the default of the video element is 1x.
* It seems to not like 10x as a rate. Might be a double digit issue.

**Comment by cjpillsbury** [comment]
@mskorsur just to re-iterate, this should be working on at least the latest version of media chrome. Here's our official docs + codesandbox example: https://www.media-chrome.org/docs/en/components/media-playback-rate-button#customize-rates
Would you mind confirming that you can reproduce this issue on the latest version of Media Chrome and, if so, providing a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.), either as a github repo, codesandbox, or similar? We can definitely re-open the issue if so.

**Comment by rtxanson** [comment]
Had the same problem, but just using the audio player. It's possible the element works correctly with video (as seen in the examples on the website), but not for audio-only elements.
