### ISSUE TITLE
Volume & Time Range height

### ISSUE THREAD

**Issue by evoactivity** [muxinc/media-chrome#689]
<img width="339" alt="image" src="https://github.com/muxinc/media-chrome/assets/83799/6fb67637-257f-4eb3-bddd-331c743cf006">

<img width="465" alt="image" src="https://github.com/muxinc/media-chrome/assets/83799/10e7b00a-e5a7-450f-816c-305aaf174c73">

Seems volume and time range height is explicitly set where the other elements auto fill available space.

Is there a reason these elements have explicit height?
https://github.com/muxinc/media-chrome/blob/e86f14f06d7c1c7eb674159826c464f91be558de/src/js/media-control-bar.js#L33

**Comment by heff** [comment]
@cjpillsbury looks like you might have been the last to touch this line. Any quick thoughts?

**Comment by cjpillsbury** [comment]
Yeah it's a known shortcoming. The tl;dr:
1. Unlike `media-chrome-button`, which is entirely "DIY" and doesn't rely on a button "under the hood," `media-chrome-range` uses a descendant `input type="range"` for its core UI
2. In order to support click/touch interaction anywhere on the component, including the "padded areas", we have to size the inner input element to the full size of the component (especially relevant for mobile/touch device use)

@luwes is hoping to eventually refactor our implementation to only rely on `input type="range"` for the "state management" bits, but we haven't yet had time.

@evoactivity Since it looks like you're using the controls in a `media-control-bar`, I recently made it so you can at least scale reliably using our `--media-control-height` CSS var that will scale all controls consistently. For a simple example, see:
https://codesandbox.io/s/media-chrome-bottom-controls-forked-726lqc?file=/index.html

**Comment by evoactivity** [comment]
The first screenshot in my original post is what happens out of the box, just by adding the live button, so merging #690 will fix that.

I've tried removing this height (and the one in media-chrome-range.js) so it fills the space automatically and made the control bar very large so there was a lot of empty space to tap. I could still control the volume slider from anywhere in the area on desktop and mobile.

**Comment by luwes** [comment]
Thanks for reporting! This is resolved in https://github.com/muxinc/media-chrome/releases/tag/v1.5.0
