### ISSUE TITLE
Height of buttons with text content isn't consistent with icons

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#89]
After #74 the height of buttons that use text isn't consistent with the height of buttons that use an icon.

<img width="435" alt="Pasted_Image_10_29_21__5_00_PM" src="https://user-images.githubusercontent.com/166/139512697-c229a6ee-23a2-4d20-89fe-d372d33b78a4.png">

Before: https://media-chrome-djevl3pei-mux.vercel.app/examples/control-elements/media-seek-backward-button.html
After: https://media-chrome-err0093s8-mux.vercel.app/examples/control-elements/media-seek-backward-button.html

**Comment by cjpillsbury** [comment]
This is called out in the notes on #74 . The updated implementation is more consistent with the way a "plain ol' `<button/>`" would behave. Given that the previous solution for consistent height between image-only use and text-only use caused issues with responsive designs, I think we should evaluate whether this is something that should be solved in a "built-in" way for our "built-in" buttons, particularly since these examples are unlikely to occur in a real-world production use case (though even if they did, I believe this should be a discussion).
