### ISSUE TITLE
How to load Youtube video /w "media-chrome/react"?

### ISSUE THREAD

**Issue by shihfu** [muxinc/media-chrome#905]
Can anyone point me to an example where the custom `<youtube-video>` element is used in react? I can't seem to figure this out.

**Comment by shihfu** [comment]
Was able to figure this out. Was getting false positive typescript error.

**Comment by raphaelpc** [comment]
Hello! Can u please post an example of how u mande this work? thanks!

**Comment by shihfu** [comment]
> Hello! Can u please share an example of how u mande this work? thanks!

I have since reverted my code back to using iframes because of a specific use-case, but I can share the code I found in my commit log.

```typescript
<>
  <Script
    type="module"
    src="https://cdn.jsdelivr.net/npm/youtube-video-element@1"
    async
  />
  <div className="video-container relative w-full" ref={ref}>
    <MediaController
      className="w-full"
    >
      <youtube-video
        src={url}
        slot="media"
        crossorigin
      ></youtube-video>
      <MediaControlBar>
        <MediaPlayButton></MediaPlayButton>
        <MediaTimeRange></MediaTimeRange>
        <MediaFullscreenButton></MediaFullscreenButton>
      </MediaControlBar>
    </MediaController>
  </div>
</>

```

**Comment by raphaelpc** [comment]
Thanks for the answer!

That gives me the error:
"Property 'youtube-video' does not exist on type 'JSX.IntrinsicElements'."
I guess that is the same typescript error you referred to.
Ideally, i guess the library should have a specific import instead of having to use `import 'youtube-video-element';`. Something like `import { YoutubeVideo } from 'youtube-video-element';`. Also makes me think if i should be using this package in React or not, instead of the default iframes solution.

[]'s

**Comment by luwes** [comment]
there is a React import nowadays, see here for some code:
https://github.com/muxinc/media-elements/blob/main/examples/nextjs/app/youtube-video/page.tsx
https://media-elements-nextjs.vercel.app/youtube-video

**Comment by raphaelpc** [comment]
Thanks @luwes !

Its strange, tought, that despite the `package.json` from `youtube-video-element` having an `"./react": "./dist/react.js"` export, the compiler gives the error `Cannot find module 'youtube-video-element/react' or its corresponding type declarations.`.

Despite the error, the component works in development mode (wont build because of the error).
But it works different from the one presented in https://www.media-chrome.org/docs/en/media-elements/youtube-video, since it works as a kind of full component and just kinds of embeds the frame from youtube on the screen, instead of working alongside `MediaController` for personalization.
The example code (https://github.com/muxinc/media-elements/blob/main/examples/nextjs/app/youtube-video/page.tsx) dont even imports `MediaController`, since `YoutubeVideo` works standalone.

[]'s

**Comment by luwes** [comment]
Here you go https://codesandbox.io/p/devbox/kt6znw

**Comment by raphaelpc** [comment]
Hey @luwes! Thanks for answering!

I got this message when trying to access your sandbox link:
```
Error: Error: (404) - URL: https://codesandbox.io/api/v1/sandboxes/kt6znw
- DATA: {"error":"Sandbox not found"} 
- ERROR: Error: (404) Not found

Version: 0.0.96
Environment: production
```

**Comment by luwes** [comment]
ah it was private, try again!

**Comment by raphaelpc** [comment]
Thanks again!

Did anyone get an error when trying to import YoutubeVideo from 'youtube-video-element/react'?

```
Type error: Cannot find module 'youtube-video-element/react' or its corresponding type declarations.

  17 | import YoutubeVideo from 'youtube-video-element/react';
```

Mine is a nextjs app and the package versions i'm using are the same as yours:
```
"media-chrome": "^3.2.3",
"youtube-video-element": "^1.1.6",
```

Don't really get why the import error is showing up. I can use the app while in dev mode, but the error will stop me from building the app.
Thanks in advance.

**Comment by luwes** [comment]
it's a TS error, try setting moduleResolution to bundler. what kind of app is it?

**Comment by raphaelpc** [comment]
Thanks, that worked ;)
[]'s

**Comment by raphaelpc** [comment]
Of note: the "MediaFullscreenButton" did NOT work for Youtube on Safari mobile (tested on an iPhone).
It worked on Chrome, both on windows and on android.
It also worked on Firefox for Windows.
